### ISSUE TITLE
wiremock-jre8-standalone ciritcal vulnerability 

### ISSUE THREAD

**Issue by adeete-zeotap** [wiremock/wiremock#1818]
The docker image: mockserver/mockserver:latest appears to be vulnerable

- [ ] Which version of WireMock you're using - wiremock/wiremock:2.32.0-alpine
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
Dockerfile  
```
FROM wiremock/wiremock:2.32.0-alpine

WORKDIR /config
COPY mappings /config/mappings
COPY __files /config/__files

ENV MOCKSERVER_MAPPINGS=/config/mappings
ENV MOCKSERVER_FILES=/config/files

CMD []
 ```

docker-compose
```
version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:2.32.0-alpine
    container_name: wiremock_demo
    volumes:
      - ${MOCKSERVER_FILES}:/home/wiremock/__files
      - ${MOCKSERVER_MAPPINGS}:/home/wiremock/mappings
    ports:
      - 8443:8080

```

```
Build -  docker build -f MockServer.Dockerfile . -t mock-server
```
```
grype unity-mock-server --fail-on medium -q    
```

Expected behaviour

No vulnerability
