### ISSUE TITLE
`ignoreExtraElements` ignores extra array elements

### ISSUE THREAD

**Issue by kubukoz** [wiremock/wiremock#1880]
I believe this behavior is inconsistent with the docs.

In the [docs](https://github.com/wiremock/wiremock.org-sources/blob/a106a665acaa6ff7d6e5dfab1b9f07221b669897/_docs/request-matching.md#less-strict-matching), we see this:

> By default different array **orderings** and **additional object attributes** will trigger a non-match. However, both of these conditions can be disabled individually.

```jsonc
{
  "request": {
    ...
    "bodyPatterns" : [ {
      "equalToJson" : "{ \"total_results\": 4  }",
      "ignoreArrayOrder" : true,
      "ignoreExtraElements" : true
    } ]
    ...
  },
  ...
}
```

Which doesn't imply that missing array elements are also affected.

In the [OpenAPI](https://github.com/wiremock/wiremock/blob/893923de294e317950080e35874e336200cc9757/src/main/resources/swagger/schemas/record-spec.yaml#L56):

```yml
          ignoreExtraElements:
            type: boolean
            default: true
            description: If equalToJson is used, matcher ignores extra elements in objects
          matcher:
```

which is very specific about extra elements in _objects_.

However, the code has this:

https://github.com/wiremock/wiremock/blob/23729a1049765d532682aa9c1b7031086436c594/src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java#L64-L67

which I believe will not only ignore extra object fields but also extra array elements.
