### ISSUE TITLE
Wiremock docker healthcheck fails when bind-address parameter is supplied

### ISSUE THREAD

**Issue by longtimeago** [wiremock/wiremock#2878]
### Problem

Docker image healthcheck fails if `--bind-address` parameter is supplied.
This prevents container from starting

### Expected behavior

Container starts without problem

### Actual behavior

Container fails to start
Inspecting docker container shows `curl: (7) Failed to connect to 127.0.0.1 port 8080 after 0 ms: Couldn't connect to server` 

### Reproduction steps

1. Use sample compose file from https://wiremock.org/docs/standalone/docker/#docker-compose but adding `--bind-address` 
```
# Sample compose file
version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:3.9.1-1"
    container_name: my_wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose", "--bind-address", "wiremock"]
```
2. Try start the stack `docker-compose -f test-compose.yml up -d`
3. Observe failed healthcheck attempts via `docker inspect {container_id}`

It will be something like
```json
            "Health": {
                "Status": "starting",
                "FailingStreak": 1,
                "Log": [
                    {
                        "Start": "2024-10-22T18:42:00.917912194+03:00",
                        "End": "2024-10-22T18:42:00.974822459+03:00",
                        "ExitCode": 1,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server\n"
                    }
                ]
            }
```
